### ISSUE TITLE
Twitch identifier available as of release 0.49

### ISSUE THREAD

**Issue by rogsachan** [nyash-qq/galaxy-plugin-twitch#10] opened 2019-09-13 20:54 UTC
see https://github.com/gogcom/galaxy-integrations-python-api/releases/tag/0.49

**Comment by Rall3n** [comment] 2019-09-14 07:51
Duplicate of #8.

The plugin should already be identified by the platform tag using the newest release (v0.4).

**Closed** 2019-09-14 14:02 UTC
